services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: elacode
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    

volumes:
  postgres_data: 